### ISSUE TITLE
The URL can't be shown

### ISSUE THREAD

**Issue by raphael10-collab** [I-CONIC-Vision-AB/wxWebMap#37]
In `CMakeLists.txt` I added the `-fpemissive` flag:

    set(GCC_WARNING_OPTIONS_FLAGS "-fpermissive")
    set(CMAKE_CXX_STANDARD 17)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GCC_WARNING_OPTIONS_FLAGS}")

and then compiled and built:

    raphy@raohy:~/wxWidgets/wxWebMap$ cmake --build builddir/
    [  7%] Building CXX object src/CMakeFiles/IconicWebMap.dir/wxMapHtml.cpp.o
    [ 15%] Building CXX object src/CMakeFiles/IconicWebMap.dir/wxMapImage.cpp.o
    [ 23%] Building CXX object src/CMakeFiles/IconicWebMap.dir/wxMapMarker.cpp.o
    /home/raphy/wxWidgets/wxWebMap/src/wxMapMarker.cpp: In constructor ‘wxMapMarker::wxMapMarker(double, double, bool)’:
    /home/raphy/wxWidgets/wxWebMap/src/wxMapMarker.cpp:13:18: warning: cast from ‘wxMapMarker*’ to ‘int’ loses precision [-fpermissive]
       13 |     cLeafletId = (int)this;
          |                  ^~~~~~~~~
    [ 30%] Building CXX object src/CMakeFiles/IconicWebMap.dir/wxMapObject.cpp.o
    [ 38%] Building CXX object src/CMakeFiles/IconicWebMap.dir/wxMapPolygon.cpp.o
    [ 46%] Building CXX object src/CMakeFiles/IconicWebMap.dir/wxWebMap.cpp.o
    [ 53%] Linking CXX shared library ../lib/libIconicWebMap.so
    [ 53%] Built target IconicWebMap
    [ 61%] Building CXX object examples/wxWebMapApp/CMakeFiles/wxWebMapApp.dir/wxWebMapApp.cpp.o
    [ 69%] Building CXX object examples/wxWebMapApp/CMakeFiles/wxWebMapApp.dir/wxWebMapFrame.cpp.o
    [ 76%] Building CXX object examples/wxWebMapApp/CMakeFiles/wxWebMapApp.dir/SourceViewDialog.cpp.o
    [ 84%] Building CXX object examples/wxWebMapApp/CMakeFiles/wxWebMapApp.dir/PolygonReader.cpp.o
    [ 92%] Building CXX object examples/wxWebMapApp/CMakeFiles/wxWebMapApp.dir/ImageReader.cpp.o
    [100%] Linking CXX executable ../../bin/wxWebMapApp
    [100%] Built target wxWebMapApp

But I get : The URL can't be shown

![image](https://github.com/I-CONIC-Vision-AB/wxWebMap/assets/70313067/0e90cdaa-f749-42f9-bb6f-86953dbe34c8)

OS: Ubuntu 23.10

**Comment by HWiman-ICONIC** [comment]
We never built wxWebMap on Linux, only made reasonable edits to make it work, but obviously not all the way. It wold be great if you worked it through all the way! I assume that you do not find and `map.html` directly under `tmp` !? 

Please debug and trace the m_url you get at line 17 in wxWebMapApp.cpp. Then try to figure out how to do the same/similar on linux. On Windows I get as shown below:
![image](https://github.com/I-CONIC-Vision-AB/wxWebMap/assets/78019492/a790ace1-e332-4875-920d-1081bc10e151)

**Comment by HWiman-ICONIC** [comment]
It could also be in wxWebMap.cpp:97 where the template html file is copied to temporary directory (check value of filename):

```
wxString filename = cOutputFileName.GetFullPath();
```

Or it could be that `file:` is missing in the url (If there is a file map.html in yout /tmp then try enter `file:/tmp/map.html` or perhaps `file:///tmp/map.html`)

**Comment by raphael10-collab** [comment]
![image](https://github.com/I-CONIC-Vision-AB/wxWebMap/assets/70313067/85603955-bd17-4943-98c2-c638afab40f3)

The path is correct with the `map.html` file present but no output

![image](https://github.com/I-CONIC-Vision-AB/wxWebMap/assets/70313067/e48c7970-fe50-4b65-a113-a7fcf105096a)

![image](https://github.com/I-CONIC-Vision-AB/wxWebMap/assets/70313067/a960b9b6-350f-4ae7-bb3d-97f6d6e191ab)

**Comment by raphael10-collab** [comment]
After "hard-coding" the path, in the Logging Window there is no error anymore, but, still, the URL can't be shown : 

![image](https://github.com/I-CONIC-Vision-AB/wxWebMap/assets/70313067/82c19ae5-ee3c-4ca7-a39c-b0310396e500)

**Comment by raphael10-collab** [comment]
Putting the entire "absolute path" to the file : `file:///home/raphy/wxWidgets/wxWebMap/data/html/map.html` makes the map visible

![image](https://github.com/I-CONIC-Vision-AB/wxWebMap/assets/70313067/79c27a46-0a66-4af4-9f75-4b62e6a01456)
